# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Code"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  code_block: ""
  code_language: ""
  content: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  code_language:
    type: select
    options:
      allow_empty: true
      allow_create: true
      values:
        - HTML
        - CSS
        - JavaScript
