# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Link
  description: An external URL with screenshot (and an optional description)
  icon: link
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  url: ""
  previewType: screenshot
  content: ""
  browserWindowMode: System

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  previewType:
    type: select
    options:
      allow_empty: false
      values:
        - screenshot
        - opengraph
  browserWindowMode:
    type: select
    options:
      values:
        - System
        - Light
        - Dark